# Generated by Django 6.0.2 on 2026-03-01 16:59

import core.models.user
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('general', 'Общий вопрос / General'), ('support', 'Техподдержка / Support'), ('bug', 'Ошибка / Bug Report'), ('feature', 'Предложение / Feature Request'), ('partnership', 'Сотрудничество / Partnership'), ('sales', 'Продажи / Sales')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('admin_reply', models.TextField(blank=True, default='', verbose_name='Ответ администратора')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
            ],
            options={
                'db_table': 'eduai_contact_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EduUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.user._avatar_path)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='student', max_length=20)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Класс')),
                ('language', models.CharField(choices=[('ru', 'RU'), ('en', 'EN'), ('kk', 'KZ')], default='ru', max_length=5)),
                ('theme', models.CharField(choices=[('dark', 'Тёмная'), ('light', 'Светлая')], default='light', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eduai_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='❓', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'eduai_faq_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='📚', max_length=10, verbose_name='Иконка (emoji)')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'db_table': 'eduai_subjects',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('context', models.CharField(blank=True, default='general', help_text='general, lesson, test, essay', max_length=30, verbose_name='Контекст')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.eduuser')),
            ],
            options={
                'db_table': 'eduai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_need', models.CharField(choices=[('none', 'Без особенностей'), ('vision', 'Слабое зрение'), ('cognitive', 'Когнитивные особенности'), ('dyslexia', 'Дислексия'), ('hearing', 'Слабый слух')], default='none', max_length=20, verbose_name='Основная потребность')),
                ('font_size', models.PositiveSmallIntegerField(default=16, verbose_name='Размер шрифта')),
                ('high_contrast', models.BooleanField(default=False, verbose_name='Высокий контраст')),
                ('text_to_speech', models.BooleanField(default=False, verbose_name='Озвучка текста')),
                ('easy_read', models.BooleanField(default=False, verbose_name='Упрощённый текст')),
                ('visual_aids', models.BooleanField(default=False, verbose_name='Визуальные опоры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='core.eduuser')),
            ],
            options={
                'db_table': 'eduai_accessibility',
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.faqcategory')),
            ],
            options={
                'db_table': 'eduai_faq_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(blank=True, help_text='["Minecraft","физика","робототехника"]', null=True, verbose_name='Интересы')),
                ('strong_topics', models.JSONField(blank=True, null=True, verbose_name='Сильные темы')),
                ('weak_topics', models.JSONField(blank=True, null=True, verbose_name='Слабые темы')),
                ('learning_style', models.CharField(choices=[('visual', 'Визуалист'), ('auditory', 'Аудиалист'), ('kinesthetic', 'Кинестетик'), ('balanced', 'Смешанный')], default='balanced', max_length=20, verbose_name='Стиль обучения')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('adaptive', 'Адаптивный')], default='medium', max_length=15, verbose_name='Уровень сложности')),
                ('total_tests_taken', models.PositiveIntegerField(default=0, verbose_name='Тестов пройдено')),
                ('avg_score', models.FloatField(default=0, verbose_name='Средний балл')),
                ('streak_days', models.PositiveSmallIntegerField(default=0, verbose_name='Дней подряд')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to='core.eduuser')),
            ],
            options={
                'db_table': 'eduai_learning_profiles',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Текст урока')),
                ('grade_level', models.PositiveSmallIntegerField(default=5, verbose_name='Класс')),
                ('easy_read_content', models.TextField(blank=True, help_text='Автоматически сгенерированная версия easy-to-read', verbose_name='Упрощённый текст')),
                ('audio_url', models.URLField(blank=True, verbose_name='Ссылка на аудио')),
                ('mindmap_data', models.JSONField(blank=True, null=True, verbose_name='Данные майнд-мапа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to='core.eduuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject')),
            ],
            options={
                'db_table': 'eduai_lessons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Текст эссе')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверено')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Оценка (0-100)')),
                ('logic_score', models.FloatField(blank=True, null=True, verbose_name='Логика')),
                ('structure_score', models.FloatField(blank=True, null=True, verbose_name='Структура')),
                ('argumentation_score', models.FloatField(blank=True, null=True, verbose_name='Аргументация')),
                ('strengths', models.TextField(blank=True, verbose_name='Сильные стороны')),
                ('weaknesses', models.TextField(blank=True, verbose_name='Слабые стороны')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('materials_to_review', models.JSONField(blank=True, null=True, verbose_name='Материалы для повторения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='core.eduuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='core.subject')),
            ],
            options={
                'db_table': 'eduai_essays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.PositiveSmallIntegerField(verbose_name='Класс')),
                ('report_text', models.TextField(verbose_name='Текст отчёта')),
                ('problem_topics', models.JSONField(blank=True, null=True, verbose_name='Проблемные темы')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('student_count', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во учеников')),
                ('avg_score', models.FloatField(default=0, verbose_name='Средний балл')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reports', to='core.eduuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reports', to='core.subject')),
            ],
            options={
                'db_table': 'eduai_class_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('variant', models.CharField(default='А', max_length=5, verbose_name='Вариант')),
                ('grade_level', models.PositiveSmallIntegerField(default=5, verbose_name='Класс')),
                ('criteria', models.TextField(blank=True, verbose_name='Критерии оценивания')),
                ('source_text', models.TextField(blank=True, verbose_name='Исходный текст для генерации')),
                ('time_limit', models.PositiveSmallIntegerField(default=45, verbose_name='Время (мин)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to='core.eduuser')),
            ],
            options={
                'db_table': 'eduai_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Баллы')),
                ('max_score', models.FloatField(default=0, verbose_name='Макс. баллов')),
                ('percentage', models.FloatField(default=0, verbose_name='Процент')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь ИИ')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='core.eduuser')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.test')),
            ],
            options={
                'db_table': 'eduai_test_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('choice', 'С вариантами ответа'), ('text', 'Открытый ответ'), ('truefalse', 'Верно/Неверно')], default='choice', max_length=15, verbose_name='Тип')),
                ('options', models.JSONField(blank=True, help_text='["вариант1","вариант2","вариант3","вариант4"]', null=True, verbose_name='Варианты ответа')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Баллы')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение к ответу')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test')),
            ],
            options={
                'db_table': 'eduai_test_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('points_earned', models.FloatField(default=0, verbose_name='Баллы')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='Комментарий ИИ')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testquestion')),
            ],
            options={
                'db_table': 'eduai_student_answers',
            },
        ),
    ]
