# Generated by Django 6.0.1 on 2026-03-21 14:50

import core.models.education
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuser',
            name='tts_speed',
            field=models.SmallIntegerField(default=0, verbose_name='TTS скорость (%)'),
        ),
        migrations.AddField(
            model_name='eduuser',
            name='tts_voice',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='TTS голос'),
        ),
        migrations.AddField(
            model_name='eduuser',
            name='tts_volume',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='TTS громкость'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.education._lesson_file_path, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
