# Generated by Django 6.0.1 on 2026-03-21 15:49

import core.models.education
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eduuser_tts_speed_eduuser_tts_voice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('grade_level', models.PositiveSmallIntegerField(default=5, verbose_name='Класс')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Макс. баллов')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=core.models.education._assignment_file_path, verbose_name='Файл')),
                ('attachment_name', models.CharField(blank=True, max_length=200, verbose_name='Имя файла')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='core.eduuser')),
            ],
            options={
                'db_table': 'eduai_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.education._submission_file_path, verbose_name='Файл')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('submitted', 'Сдано'), ('graded', 'Оценено'), ('returned', 'Возвращено')], default='submitted', max_length=15, verbose_name='Статус')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Баллы')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.eduuser')),
            ],
            options={
                'db_table': 'eduai_submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
