# Generated by Django 6.0.1 on 2026-03-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.eduuser'),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_reports', to='core.eduuser'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to='core.eduuser'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_attempts', to='core.eduuser'),
        ),
    ]
