# Generated by Django 6.0.2 on 2026-03-23 10:29

import core.models.organization
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_soft_delete_protect_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'eduai_organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='eduuser',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель'), ('school_admin', 'Администратор школы'), ('admin', 'Администратор платформы')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='eduuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=core.models.organization._generate_key, max_length=64, unique=True, verbose_name='Ключ')),
                ('key_type', models.CharField(choices=[('master', 'Мастер-ключ (для школьного админа)'), ('teacher', 'Ключ учителя')], default='teacher', max_length=10, verbose_name='Тип')),
                ('grades', models.CharField(blank=True, help_text='Список классов через запятую, напр. 5,6,7', max_length=50, verbose_name='Классы')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='core.organization')),
                ('subject', models.ForeignKey(blank=True, help_text='Предмет учителя (только для teacher-ключей)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_keys', to='core.eduuser')),
            ],
            options={
                'db_table': 'eduai_org_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
