# Generated by Django 6.0.2 on 2026-03-27 15:23

import core.models.education
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_alter_eduuser_role_eduuser_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.education._submission_extra_file_path)),
                ('file_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.assignmentsubmission')),
            ],
            options={
                'db_table': 'eduai_submission_files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
