# Generated by Django 6.0.2 on 2026-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuser',
            name='tz',
            field=models.CharField(default='Asia/Almaty', max_length=40, verbose_name='Часовой пояс'),
        ),
    ]
