# Generated by Django 6.0.1 on 2026-03-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduuser',
            name='ai_requests_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счётчика ИИ'),
        ),
        migrations.AddField(
            model_name='eduuser',
            name='ai_requests_today',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Запросы ИИ сегодня'),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_reports', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='essays', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='core.subject'),
        ),
    ]
