# Generated by Django 6.0.2 on 2026-03-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_protect_subject_fk_ai_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityprofile',
            name='font_family',
            field=models.CharField(choices=[('default', 'Inter (стандартный)'), ('opendyslexic', 'OpenDyslexic'), ('lexend', 'Lexend'), ('atkinson', 'Atkinson Hyperlegible'), ('comic', 'Comic Neue')], default='default', max_length=20, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='accessibilityprofile',
            name='voice_input',
            field=models.BooleanField(default=False, verbose_name='Голосовой ввод'),
        ),
        migrations.AddField(
            model_name='accessibilityprofile',
            name='zen_mode',
            field=models.BooleanField(default=False, verbose_name='Дзен-режим (СДВГ)'),
        ),
    ]
