# Generated by Django 6.0.2 on 2026-03-30 11:30

from django.db import migrations, models


def reset_old_fonts(apps, schema_editor):
    AccessibilityProfile = apps.get_model('core', 'AccessibilityProfile')
    old_fonts = ['opendyslexic', 'lexend', 'atkinson', 'comic']
    AccessibilityProfile.objects.filter(font_family__in=old_fonts).update(font_family='default')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accessibility_font_zen_voice'),
    ]

    operations = [
        migrations.RunPython(reset_old_fonts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='font_family',
            field=models.CharField(choices=[('default', 'Inter (стандартный)'), ('comfortaa', 'Comfortaa'), ('ptsans', 'PT Sans'), ('pangolin', 'Pangolin'), ('arial', 'Arial'), ('verdana', 'Verdana'), ('georgia', 'Georgia'), ('times', 'Times New Roman'), ('courier', 'Courier New')], default='default', max_length=20, verbose_name='Шрифт'),
        ),
    ]
