# Generated by Django 6.0.2 on 2026-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_font_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='font_family',
            field=models.CharField(choices=[('default', 'Inter (стандартный)'), ('opendyslexic', 'OpenDyslexic'), ('comfortaa', 'Comfortaa'), ('ptsans', 'PT Sans'), ('pangolin', 'Pangolin'), ('arial', 'Arial'), ('verdana', 'Verdana'), ('georgia', 'Georgia'), ('times', 'Times New Roman'), ('courier', 'Courier New')], default='default', max_length=20, verbose_name='Шрифт'),
        ),
    ]
