# Generated by Django 6.0.2 on 2026-03-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_opendyslexic_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkey',
            name='key_type',
            field=models.CharField(choices=[('master', 'Мастер-ключ (для школьного админа)'), ('teacher', 'Ключ учителя'), ('student', 'Ключ ученика')], default='teacher', max_length=10, verbose_name='Тип'),
        ),
    ]
