# Generated by Django 6.0.2 on 2026-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_organizationkey_key_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (англ)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (каз)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (рус)'),
        ),
    ]
