# Generated by Django 6.0.2 on 2026-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_subject_localization'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='answer_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='answer_kk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='question_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='question_kk',
            field=models.TextField(blank=True),
        ),
    ]
